- name: provision aws resources
  hosts: localhost
  tasks:
    - name: launch cloudformation
      cloudformation:
        stack_name: "telemetry-spark-cloudformation"
        state: "present"
        region: "{{telemetry_analysis_region}}"
        disable_rollback: true
        template: "{{playbook_dir}}/files/cloudformation.json"
        tags:
          type: "telemetry"
          application: "spark"
        template_parameters:
          TelemetryAnalysisCodeBucket: "{{telemetry_analysis_code_bucket}}"
          TelemetryAnalysisSparkEMRBucket: "{{telemetry_analysis_spark_emr_bucket}}"
          TelemetryAnalysisPublicBucket: "{{telemetry_analysis_public_bucket}}"
          TelemetryAnalysisPrivateBucket: "{{telemetry_analysis_private_bucket}}"
      register: cloudformation

    - name: create bucket
      s3: bucket={{telemetry_analysis_spark_emr_bucket}} region={{telemetry_analysis_region}} mode=create

    - name: copy private EMR files
      include: render_and_copy_to_s3.yml file={{item}} permission="private"
      with_items:
        - steps/batch.sh
        - steps/zeppelin/zeppelin.sh
        - steps/zeppelin/note.json
        - configuration/zeppelin/interpreter.json
        - bootstrap/telemetry.sh

    - name: copy public EMR files
      include: render_and_copy_to_s3.yml file={{item}} permission="public-read"
      with_items:
        - configuration/configuration.json
